import type {
  NetworkNode,
  NetworkTopologySnapshot,
  ProbeResult,
  ReachabilityState,
  RouteEntry,
  RoutingProtocol,
} from './network-map';
import type { GatewayConfig, UniversalIngressEnvelope } from './types';

/** Network stack layer that produced an observation or decision. */
export type NetworkStackLayer =
  | 'L2_ETHERNET'
  | 'L2_WIFI'
  | 'L2_BLE'
  | 'L2_LORA'
  | 'L2_ESP_NOW'
  | 'L2_ZIGBEE'
  | 'L3_IPV4'
  | 'L3_IPV6'
  | 'L3_ARP'
  | 'L3_NDP'
  | 'L3_VLAN'
  | 'L4_TCP'
  | 'L4_UDP'
  | 'L5_MQTT'
  | 'L5_HTTP'
  | 'L5_COAP'
  | 'L5_MODBUS'
  | 'L5_OPCUA'
  | 'L5_BACNET'
  | 'L5_DNP3'
  | 'L5_SERIAL'
  | 'L5_WEBSOCKET'
  | 'FIELD_CAN'
  | 'FIELD_PROFINET'
  | 'FIELD_ETHERNET_IP'
  | 'CONTROL_DHCP'
  | 'CONTROL_DHCPV6'
  | 'CONTROL_SLAAC'
  | 'CONTROL_ROUTING'
  | 'APPLICATION';

/** Classes of network blocker AEGIS can infer from telemetry and probes. */
export type NetworkBlockerType =
  | 'NAT_BOUNDARY'
  | 'FIREWALL_DROP'
  | 'PORT_FORWARD_MISSING'
  | 'DHCP_CHURN'
  | 'SLAAC_PREFIX_CHANGE'
  | 'VLAN_ISOLATION'
  | 'ROUTE_FLAP'
  | 'ASYMMETRIC_ROUTE'
  | 'BROADCAST_NOISE'
  | 'HIGH_LATENCY'
  | 'HIGH_PACKET_LOSS'
  | 'HIGH_RECONNECT_RATE'
  | 'MTU_BLACKHOLE'
  | 'AGGREGATOR_ID_COLLISION'
  | 'PLAINTEXT_OPEN_WIFI'
  | 'OT_PLAINTEXT_PROTOCOL'
  | 'MULTICAST_STORM'
  | 'ROGUE_DHCP'
  | 'ARP_SPOOFING'
  | 'CONTROL_PLANE_ANOMALY'
  | 'UNKNOWN_REACHABILITY';

/** Network action intent generated by the intelligence engine. */
export type NetworkActionType =
  | 'PROBE_NEXT_HOP'
  | 'PREFER_LOCAL_ROUTE'
  | 'HOLD_REMOTE_FANOUT'
  | 'THROTTLE_LOW_PRIORITY'
  | 'REQUIRE_ENCRYPTED_INGRESS'
  | 'INSPECT_FIREWALL_RULE'
  | 'INSPECT_NAT_OR_PORT_FORWARD'
  | 'PIN_DEVICE_TO_SEGMENT'
  | 'SPLIT_AGGREGATOR_STREAM'
  | 'RAISE_OPERATOR_ALERT'
  | 'UPDATE_BASELINE'
  | 'NOOP';

/** Severity used by network findings and action plans. */
export type NetworkFindingSeverity = 'INFO' | 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/** Runtime mode of the network intelligence engine. */
export type NetworkIntelligenceMode = 'OBSERVE_ONLY' | 'RECOMMEND' | 'AUTO_SAFE';

/** Operator-tunable thresholds for real-world network learning. */
export interface NetworkIntelligenceThresholds {
  readonly minSamples: number;
  readonly highLatencyMs: number;
  readonly highPacketLossRatio: number;
  readonly highReconnects: number;
  readonly latencyZScore: number;
  readonly packetLossZScore: number;
  readonly reconnectZScore: number;
  readonly routeFlapWindowMs: number;
  readonly routeFlapCount: number;
  readonly staleNodeMs: number;
  readonly preferredRouteScore: number;
  readonly openWifiPlaintextRisk: number;
  readonly highMulticastPacketsPerSecond: number;
  readonly controlPlaneAnomalyScore: number;
}

/** Configuration for the network intelligence engine. */
export interface NetworkIntelligenceConfig {
  readonly enabled: boolean;
  readonly mode: NetworkIntelligenceMode;
  readonly learnEveryObservation: boolean;
  readonly actionLimit: number;
  readonly thresholds: NetworkIntelligenceThresholds;
}

/** One network condition sample consumed by the intelligence engine. */
export interface NetworkIntelligenceObservation {
  readonly key: string;
  readonly deviceId?: string;
  readonly segmentId?: string;
  readonly routeKey?: string;
  readonly layers: readonly NetworkStackLayer[];
  readonly latencyMs?: number;
  readonly packetLossRatio?: number;
  readonly reconnects?: number;
  readonly jitterMs?: number;
  readonly throughputBps?: number;
  readonly rssiDbm?: number;
  readonly mtuBytes?: number;
  readonly vlanId?: number;
  readonly addressFamily?: 'IPv4' | 'IPv6' | 'DUAL_STACK' | 'UNKNOWN';
  readonly dhcpLeaseSeconds?: number;
  readonly routingProtocol?: RoutingProtocol;
  readonly broadcast?: boolean;
  readonly multicastPacketsPerSecond?: number;
  readonly controlPlaneAnomalyScore?: number;
  readonly encrypted?: boolean;
  readonly aggregatorId?: string;
  readonly embeddedDeviceIds?: readonly string[];
  readonly observedAt?: string;
  readonly metadata?: Record<string, unknown>;
}

/** Learned baseline for one path, segment, route, or device key. */
export interface LearnedNetworkBaseline {
  readonly key: string;
  readonly samples: number;
  readonly firstSeen: string;
  readonly lastSeen: string;
  readonly layers: readonly NetworkStackLayer[];
  readonly ewmaLatencyMs: number;
  readonly meanLatencyMs: number;
  readonly latencyStddevMs: number;
  readonly ewmaPacketLossRatio: number;
  readonly meanPacketLossRatio: number;
  readonly packetLossStddev: number;
  readonly ewmaReconnects: number;
  readonly meanReconnects: number;
  readonly reconnectStddev: number;
  readonly ewmaJitterMs: number;
  readonly availabilityScore: number;
  readonly routeScore: number;
  readonly encryptedRatio: number;
  readonly broadcastRatio: number;
  readonly addressFamilies: readonly string[];
  readonly routingProtocols: readonly RoutingProtocol[];
  readonly aggregators: readonly string[];
}

/** Finding derived from topology, probes, or condition learning. */
export interface NetworkFinding {
  readonly id: string;
  readonly type: NetworkBlockerType;
  readonly severity: NetworkFindingSeverity;
  readonly key: string;
  readonly message: string;
  readonly observedAt: string;
  readonly evidence: Record<string, unknown>;
}

/** Action plan emitted by the network intelligence engine. */
export interface NetworkActionPlan {
  readonly id: string;
  readonly type: NetworkActionType;
  readonly severity: NetworkFindingSeverity;
  readonly target: string;
  readonly reason: string;
  readonly createdAt: string;
  readonly status: 'RECOMMENDED' | 'EXECUTED' | 'SUPPRESSED';
  readonly evidence: Record<string, unknown>;
}

/** Gateway control effects returned for one ingress event. */
export interface NetworkControlDecision {
  readonly holdRemoteFanout: boolean;
  readonly throttleLowPriority: boolean;
  readonly requireEncryptedIngress: boolean;
  readonly preferredRoute?: RouteEntry;
  readonly findings: readonly NetworkFinding[];
  readonly actions: readonly NetworkActionPlan[];
}

/** Operator-facing network intelligence snapshot. */
export interface NetworkIntelligenceSnapshot {
  readonly mode: NetworkIntelligenceMode;
  readonly enabled: boolean;
  readonly baselines: readonly LearnedNetworkBaseline[];
  readonly findings: readonly NetworkFinding[];
  readonly actions: readonly NetworkActionPlan[];
  readonly recommendations: readonly RouteRecommendation[];
  readonly topologyDigest: NetworkTopologyDigest;
}

/** Recommended route ranking for a known destination. */
export interface RouteRecommendation {
  readonly destination: string;
  readonly selected: RouteEntry;
  readonly alternatives: readonly RouteCandidate[];
  readonly reason: string;
}

/** Scored route candidate. */
export interface RouteCandidate {
  readonly route: RouteEntry;
  readonly score: number;
  readonly baselineKey: string;
  readonly blockers: readonly NetworkBlockerType[];
}

/** Compact counts used by health checks and UI cards. */
export interface NetworkTopologyDigest {
  readonly nodes: number;
  readonly links: number;
  readonly routes: number;
  readonly reachable: number;
  readonly degraded: number;
  readonly unreachable: number;
  readonly unknown: number;
  readonly protocols: Record<string, number>;
  readonly segments: Record<string, number>;
}

interface RunningNumberStats {
  count: number;
  mean: number;
  m2: number;
}

interface MutableBaseline {
  key: string;
  samples: number;
  firstSeen: string;
  lastSeen: string;
  layers: Set<NetworkStackLayer>;
  latency: RunningNumberStats;
  packetLoss: RunningNumberStats;
  reconnects: RunningNumberStats;
  ewmaLatencyMs: number;
  ewmaPacketLossRatio: number;
  ewmaReconnects: number;
  ewmaJitterMs: number;
  availabilityScore: number;
  routeScore: number;
  encryptedCount: number;
  broadcastCount: number;
  addressFamilies: Set<string>;
  routingProtocols: Set<RoutingProtocol>;
  aggregators: Set<string>;
}

interface RouteHistoryItem {
  readonly nextHop: string;
  readonly metric: number;
  readonly observedAtMs: number;
}

const EWMA_ALPHA_FAST = 0.35;
const EWMA_ALPHA_SLOW = 0.12;
const SCORE_MAX_LATENCY_MS = 2_000;
const SCORE_MAX_RECONNECTS = 10;
const SCORE_MIN = 0;
const SCORE_MAX = 1;
const FINDING_RETENTION = 250;
const ACTION_RETENTION = 250;

/** Default threshold set for mixed LAN, mesh, serial, and cloud edge networks. */
export const DEFAULT_NETWORK_INTELLIGENCE_THRESHOLDS: NetworkIntelligenceThresholds = {
  minSamples: 5,
  highLatencyMs: 500,
  highPacketLossRatio: 0.08,
  highReconnects: 3,
  latencyZScore: 3,
  packetLossZScore: 3,
  reconnectZScore: 3,
  routeFlapWindowMs: 60_000,
  routeFlapCount: 3,
  staleNodeMs: 120_000,
  preferredRouteScore: 0.7,
  openWifiPlaintextRisk: 0.65,
  highMulticastPacketsPerSecond: 500,
  controlPlaneAnomalyScore: 0.8,
};

/** Default configuration for the active learning and action engine. */
export const DEFAULT_NETWORK_INTELLIGENCE_CONFIG: NetworkIntelligenceConfig = {
  enabled: true,
  mode: 'AUTO_SAFE',
  learnEveryObservation: true,
  actionLimit: 250,
  thresholds: DEFAULT_NETWORK_INTELLIGENCE_THRESHOLDS,
};

/** Learns network behavior, classifies blockers, and emits safe gateway actions. */
export class NetworkIntelligenceEngine {
  private readonly baselines = new Map<string, MutableBaseline>();
  private readonly findings: NetworkFinding[] = [];
  private readonly actions: NetworkActionPlan[] = [];
  private readonly routeHistory = new Map<string, RouteHistoryItem[]>();
  private sequence = 0;
  private lastTopology: NetworkTopologySnapshot | undefined;

  public constructor(private readonly config = DEFAULT_NETWORK_INTELLIGENCE_CONFIG) {}

  /** Observes accepted ingress and returns immediate control effects for this event. */
  public observeEnvelope(
    envelope: UniversalIngressEnvelope,
    topology: NetworkTopologySnapshot,
    gatewayConfig: GatewayConfig,
  ): NetworkControlDecision {
    this.lastTopology = topology;
    if (!this.config.enabled) {
      return emptyDecision();
    }
    const observedAt = normalizeTime(envelope.timestamp);
    const observation = observationFromEnvelope(envelope);
    const findings = this.observeCondition(observation, topology);
    const routeFindings = this.observeRoutes(topology.routes, observedAt);
    const segmentFindings = this.inspectSegments(envelope, gatewayConfig, topology, observedAt);
    const aggregatorFindings = this.inspectAggregator(envelope, observedAt);
    this.rememberFindings([...segmentFindings, ...aggregatorFindings]);
    const allFindings = [...findings, ...routeFindings, ...segmentFindings, ...aggregatorFindings];
    const actions = this.planActions(allFindings, observation.key, topology, observedAt);
    const preferredRoute = this.recommendRoute(envelope.deviceId, topology)?.selected;
    return this.controlDecision(allFindings, actions, preferredRoute);
  }

  /** Observes a standalone condition sample from SDK callers or APIs. */
  public observeCondition(
    observation: NetworkIntelligenceObservation,
    topology = this.lastTopology,
  ): readonly NetworkFinding[] {
    if (!this.config.enabled) {
      return [];
    }
    const observedAt = normalizeTime(observation.observedAt);
    const baseline = this.upsertBaseline(observation, observedAt);
    const findings: NetworkFinding[] = [];
    findings.push(...this.detectStatisticalDeviations(observation, baseline, observedAt));
    findings.push(...this.detectStructuralBlockers(observation, baseline, observedAt));
    if (topology !== undefined) {
      findings.push(...this.detectTopologyBlockers(topology, observedAt));
    }
    this.rememberFindings(findings);
    const actions = this.planActions(findings, observation.key, topology, observedAt);
    this.rememberActions(actions);
    return findings;
  }

  /** Observes a reachability probe and converts failures into blocker evidence. */
  public observeProbe(result: ProbeResult): NetworkControlDecision {
    if (!this.config.enabled) {
      return emptyDecision();
    }
    const observedAt = normalizeTime(result.observedAt);
    const key = `probe:${result.target.nodeId}:${result.target.protocol}`;
    const observation: NetworkIntelligenceObservation = {
      key,
      deviceId: result.target.nodeId,
      layers: probeLayers(result.target.protocol),
      packetLossRatio: result.reachable ? 0 : 1,
      reconnects: result.reachable ? 0 : 1,
      encrypted: result.target.protocol === 'HTTP' && result.target.address.startsWith('https://'),
      observedAt,
      ...(result.latencyMs === undefined ? {} : { latencyMs: result.latencyMs }),
      metadata: {
        address: result.target.address,
        protocol: result.target.protocol,
        port: result.target.port,
        path: result.target.path,
        error: result.error,
      },
    };
    const findings = [...this.observeCondition(observation), ...this.classifyProbeFailure(result)];
    this.rememberFindings(findings);
    const actions = this.planActions(findings, key, this.lastTopology, observedAt);
    this.rememberActions(actions);
    return this.controlDecision(findings, actions, undefined);
  }

  /** Updates route history and detects route flapping or metric churn. */
  public observeRoutes(
    routes: readonly RouteEntry[],
    observedAt = new Date().toISOString(),
  ): readonly NetworkFinding[] {
    if (!this.config.enabled) {
      return [];
    }
    const observedAtMs = Date.parse(observedAt);
    const findings: NetworkFinding[] = [];
    for (const route of routes) {
      const key = route.destination;
      const history = this.routeHistory.get(key) ?? [];
      const next = [
        ...history.filter(
          (item) => observedAtMs - item.observedAtMs <= this.config.thresholds.routeFlapWindowMs,
        ),
        { nextHop: route.nextHop, metric: route.metric, observedAtMs },
      ];
      this.routeHistory.set(key, next);
      const distinctNextHops = new Set(next.map((item) => item.nextHop));
      const distinctMetrics = new Set(next.map((item) => item.metric));
      if (
        distinctNextHops.size + distinctMetrics.size >= this.config.thresholds.routeFlapCount &&
        next.length >= this.config.thresholds.routeFlapCount
      ) {
        findings.push(
          this.finding('ROUTE_FLAP', 'MEDIUM', `route:${route.destination}`, observedAt, {
            destination: route.destination,
            nextHops: [...distinctNextHops],
            metrics: [...distinctMetrics],
            protocol: route.protocol,
          }),
        );
      }
    }
    this.rememberFindings(findings);
    return findings;
  }

  /** Produces scored route recommendations for every known destination. */
  public routeRecommendations(topology = this.lastTopology): readonly RouteRecommendation[] {
    if (topology === undefined) {
      return [];
    }
    const byDestination = groupBy(topology.routes, (route) => route.destination);
    return [...byDestination.entries()]
      .map(([destination, routes]) => this.recommendRouteFromRoutes(destination, routes, topology))
      .filter((item): item is RouteRecommendation => item !== undefined)
      .sort((left, right) => left.destination.localeCompare(right.destination));
  }

  /** Returns a stable operator/API snapshot of learned network intelligence. */
  public snapshot(topology = this.lastTopology): NetworkIntelligenceSnapshot {
    const recommendations = this.routeRecommendations(topology);
    return {
      enabled: this.config.enabled,
      mode: this.config.mode,
      baselines: [...this.baselines.values()]
        .map(publicBaseline)
        .sort((left, right) => left.key.localeCompare(right.key)),
      findings: [...this.findings],
      actions: [...this.actions],
      recommendations,
      topologyDigest: topologyDigest(topology),
    };
  }

  private recommendRoute(
    destination: string,
    topology: NetworkTopologySnapshot,
  ): RouteRecommendation | undefined {
    const routes = topology.routes.filter((route) => route.destination === destination);
    return this.recommendRouteFromRoutes(destination, routes, topology);
  }

  private recommendRouteFromRoutes(
    destination: string,
    routes: readonly RouteEntry[],
    topology: NetworkTopologySnapshot,
  ): RouteRecommendation | undefined {
    if (routes.length === 0) {
      return undefined;
    }
    const candidates = routes
      .map((route) => this.scoreRoute(route, topology))
      .sort((left, right) => right.score - left.score || left.route.metric - right.route.metric);
    const selected = candidates[0];
    if (selected === undefined) {
      return undefined;
    }
    return {
      destination,
      selected: selected.route,
      alternatives: candidates,
      reason:
        selected.score >= this.config.thresholds.preferredRouteScore
          ? 'highest learned route score'
          : 'best available route is below preferred threshold',
    };
  }

  private scoreRoute(route: RouteEntry, topology: NetworkTopologySnapshot): RouteCandidate {
    const baselineKey = routeBaselineKey(route);
    const baseline = this.baselines.get(baselineKey) ?? this.baselines.get(route.destination);
    const nextHop = topology.nodes.find((node) => node.id === route.nextHop);
    const link = topology.links.find(
      (candidate) => candidate.to === route.destination && candidate.from === route.nextHop,
    );
    const nextHopReachabilityScore = scoreReachability(nextHop?.reachability ?? 'UNKNOWN');
    const metricScore = clamp(1 - route.metric / 100, SCORE_MIN, SCORE_MAX);
    const baselineScore = baseline?.routeScore ?? 0.55;
    const protocolScore = protocolPreference(route.protocol);
    const linkCostScore =
      link === undefined ? 0.55 : clamp(1 - link.cost / 100, SCORE_MIN, SCORE_MAX);
    const score = clamp(
      baselineScore * 0.35 +
        nextHopReachabilityScore * 0.25 +
        metricScore * 0.18 +
        protocolScore * 0.12 +
        linkCostScore * 0.1,
      SCORE_MIN,
      SCORE_MAX,
    );
    return {
      route,
      score,
      baselineKey,
      blockers: this.findings
        .filter(
          (finding) =>
            finding.key.includes(route.destination) ||
            finding.key.includes(route.nextHop) ||
            finding.key.includes(baselineKey),
        )
        .map((finding) => finding.type),
    };
  }

  private upsertBaseline(
    observation: NetworkIntelligenceObservation,
    observedAt: string,
  ): MutableBaseline {
    const current = this.baselines.get(observation.key);
    const baseline =
      current ??
      ({
        key: observation.key,
        samples: 0,
        firstSeen: observedAt,
        lastSeen: observedAt,
        layers: new Set<NetworkStackLayer>(),
        latency: emptyStats(),
        packetLoss: emptyStats(),
        reconnects: emptyStats(),
        ewmaLatencyMs: observation.latencyMs ?? 0,
        ewmaPacketLossRatio: observation.packetLossRatio ?? 0,
        ewmaReconnects: observation.reconnects ?? 0,
        ewmaJitterMs: observation.jitterMs ?? 0,
        availabilityScore: 1,
        routeScore: 1,
        encryptedCount: 0,
        broadcastCount: 0,
        addressFamilies: new Set<string>(),
        routingProtocols: new Set<RoutingProtocol>(),
        aggregators: new Set<string>(),
      } satisfies MutableBaseline);
    baseline.samples += 1;
    baseline.lastSeen = observedAt;
    for (const layer of observation.layers) {
      baseline.layers.add(layer);
    }
    if (observation.latencyMs !== undefined) {
      baseline.latency = updateStats(baseline.latency, observation.latencyMs);
      baseline.ewmaLatencyMs = ewma(baseline.ewmaLatencyMs, observation.latencyMs, EWMA_ALPHA_FAST);
    }
    if (observation.packetLossRatio !== undefined) {
      baseline.packetLoss = updateStats(baseline.packetLoss, observation.packetLossRatio);
      baseline.ewmaPacketLossRatio = ewma(
        baseline.ewmaPacketLossRatio,
        observation.packetLossRatio,
        EWMA_ALPHA_FAST,
      );
    }
    if (observation.reconnects !== undefined) {
      baseline.reconnects = updateStats(baseline.reconnects, observation.reconnects);
      baseline.ewmaReconnects = ewma(
        baseline.ewmaReconnects,
        observation.reconnects,
        EWMA_ALPHA_SLOW,
      );
    }
    if (observation.jitterMs !== undefined) {
      baseline.ewmaJitterMs = ewma(baseline.ewmaJitterMs, observation.jitterMs, EWMA_ALPHA_FAST);
    }
    if (observation.encrypted === true) {
      baseline.encryptedCount += 1;
    }
    if (observation.broadcast === true) {
      baseline.broadcastCount += 1;
    }
    if (observation.addressFamily !== undefined) {
      baseline.addressFamilies.add(observation.addressFamily);
    }
    if (observation.routingProtocol !== undefined) {
      baseline.routingProtocols.add(observation.routingProtocol);
    }
    if (observation.aggregatorId !== undefined) {
      baseline.aggregators.add(observation.aggregatorId);
    }
    baseline.availabilityScore = clamp(1 - baseline.ewmaPacketLossRatio, SCORE_MIN, SCORE_MAX);
    baseline.routeScore = computePathScore(baseline);
    this.baselines.set(observation.key, baseline);
    return baseline;
  }

  private detectStatisticalDeviations(
    observation: NetworkIntelligenceObservation,
    baseline: MutableBaseline,
    observedAt: string,
  ): NetworkFinding[] {
    const findings: NetworkFinding[] = [];
    if (
      observation.latencyMs !== undefined &&
      (observation.latencyMs >= this.config.thresholds.highLatencyMs ||
        zScore(observation.latencyMs, baseline.latency) >= this.config.thresholds.latencyZScore)
    ) {
      findings.push(
        this.finding('HIGH_LATENCY', 'MEDIUM', observation.key, observedAt, {
          latencyMs: observation.latencyMs,
          meanLatencyMs: baseline.latency.mean,
          ewmaLatencyMs: baseline.ewmaLatencyMs,
        }),
      );
    }
    if (
      observation.packetLossRatio !== undefined &&
      (observation.packetLossRatio >= this.config.thresholds.highPacketLossRatio ||
        zScore(observation.packetLossRatio, baseline.packetLoss) >=
          this.config.thresholds.packetLossZScore)
    ) {
      findings.push(
        this.finding('HIGH_PACKET_LOSS', 'HIGH', observation.key, observedAt, {
          packetLossRatio: observation.packetLossRatio,
          meanPacketLossRatio: baseline.packetLoss.mean,
          availabilityScore: baseline.availabilityScore,
        }),
      );
    }
    if (
      observation.reconnects !== undefined &&
      (observation.reconnects >= this.config.thresholds.highReconnects ||
        zScore(observation.reconnects, baseline.reconnects) >=
          this.config.thresholds.reconnectZScore)
    ) {
      findings.push(
        this.finding('HIGH_RECONNECT_RATE', 'MEDIUM', observation.key, observedAt, {
          reconnects: observation.reconnects,
          meanReconnects: baseline.reconnects.mean,
        }),
      );
    }
    return findings;
  }

  private detectStructuralBlockers(
    observation: NetworkIntelligenceObservation,
    baseline: MutableBaseline,
    observedAt: string,
  ): NetworkFinding[] {
    const findings: NetworkFinding[] = [];
    const metadata = observation.metadata ?? {};
    const error = stringValue(metadata.error).toLowerCase();
    if (error.includes('timeout') || error.includes('etimedout')) {
      findings.push(
        this.finding('FIREWALL_DROP', 'HIGH', observation.key, observedAt, {
          error,
          layers: observation.layers,
        }),
      );
    }
    if (error.includes('econnrefused') || error.includes('connection refused')) {
      findings.push(
        this.finding('PORT_FORWARD_MISSING', 'MEDIUM', observation.key, observedAt, {
          error,
          address: metadata.address,
          port: metadata.port,
        }),
      );
    }
    if (truthy(metadata.natDetected) || truthy(metadata.privateToPublicBoundary)) {
      findings.push(
        this.finding('NAT_BOUNDARY', 'LOW', observation.key, observedAt, {
          natDetected: metadata.natDetected,
          privateToPublicBoundary: metadata.privateToPublicBoundary,
        }),
      );
    }
    if (truthy(metadata.vlanMismatch) || observation.layers.includes('L3_VLAN')) {
      const vlanIsolation =
        metadata.vlanMismatch === true || metadata.peerForwardingBlocked === true;
      if (vlanIsolation) {
        findings.push(
          this.finding('VLAN_ISOLATION', 'MEDIUM', observation.key, observedAt, {
            vlanId: observation.vlanId,
            peerForwardingBlocked: metadata.peerForwardingBlocked,
          }),
        );
      }
    }
    if (truthy(metadata.dhcpAddressChanged) || truthy(metadata.leaseExpiredUnexpectedly)) {
      findings.push(
        this.finding('DHCP_CHURN', 'MEDIUM', observation.key, observedAt, {
          dhcpLeaseSeconds: observation.dhcpLeaseSeconds,
          addressFamily: observation.addressFamily,
        }),
      );
    }
    if (truthy(metadata.slaacPrefixChanged) || truthy(metadata.ipv6TemporaryAddressRotated)) {
      findings.push(
        this.finding('SLAAC_PREFIX_CHANGE', 'LOW', observation.key, observedAt, {
          addressFamily: observation.addressFamily,
          metadata,
        }),
      );
    }
    if (truthy(metadata.asymmetricRoute)) {
      findings.push(
        this.finding('ASYMMETRIC_ROUTE', 'MEDIUM', observation.key, observedAt, {
          routeKey: observation.routeKey,
          metadata,
        }),
      );
    }
    if (truthy(metadata.mtuBlackhole) || truthy(metadata.fragmentationObserved)) {
      findings.push(
        this.finding('MTU_BLACKHOLE', 'MEDIUM', observation.key, observedAt, {
          mtuBytes: observation.mtuBytes,
          fragmentationObserved: metadata.fragmentationObserved,
        }),
      );
    }
    const encryptedShare = ratio(baseline.encryptedCount, baseline.samples);
    const broadcastShare = ratio(baseline.broadcastCount, baseline.samples);
    const openWifiPlaintextRisk =
      broadcastShare * 0.35 +
      (1 - encryptedShare) * 0.45 +
      (observation.layers.includes('L2_WIFI') ? 0.2 : 0);
    if (
      observation.broadcast === true &&
      observation.encrypted === false &&
      observation.layers.includes('L2_WIFI') &&
      openWifiPlaintextRisk >= this.config.thresholds.openWifiPlaintextRisk
    ) {
      findings.push(
        this.finding('PLAINTEXT_OPEN_WIFI', 'HIGH', observation.key, observedAt, {
          openWifiPlaintextRisk,
          encryptedRatio: encryptedShare,
          broadcastRatio: broadcastShare,
        }),
      );
    }
    if (observation.broadcast === true && broadcastShare > 0.7) {
      findings.push(
        this.finding('BROADCAST_NOISE', 'LOW', observation.key, observedAt, {
          broadcastRatio: broadcastShare,
          samples: baseline.samples,
        }),
      );
    }
    if (
      observation.multicastPacketsPerSecond !== undefined &&
      observation.multicastPacketsPerSecond >= this.config.thresholds.highMulticastPacketsPerSecond
    ) {
      findings.push(
        this.finding('MULTICAST_STORM', 'MEDIUM', observation.key, observedAt, {
          multicastPacketsPerSecond: observation.multicastPacketsPerSecond,
          threshold: this.config.thresholds.highMulticastPacketsPerSecond,
        }),
      );
    }
    if (
      observation.controlPlaneAnomalyScore !== undefined &&
      observation.controlPlaneAnomalyScore >= this.config.thresholds.controlPlaneAnomalyScore
    ) {
      findings.push(
        this.finding('CONTROL_PLANE_ANOMALY', 'HIGH', observation.key, observedAt, {
          controlPlaneAnomalyScore: observation.controlPlaneAnomalyScore,
          threshold: this.config.thresholds.controlPlaneAnomalyScore,
        }),
      );
    }
    if (truthy(metadata.rogueDhcp) || truthy(metadata.dhcpServerChanged)) {
      findings.push(
        this.finding('ROGUE_DHCP', 'HIGH', observation.key, observedAt, {
          dhcpServer: metadata.dhcpServer,
          previousDhcpServer: metadata.previousDhcpServer,
        }),
      );
    }
    if (truthy(metadata.arpConflict) || truthy(metadata.duplicateMac)) {
      findings.push(
        this.finding('ARP_SPOOFING', 'HIGH', observation.key, observedAt, {
          mac: metadata.mac,
          previousMac: metadata.previousMac,
          address: metadata.address,
        }),
      );
    }
    if (
      observation.encrypted === false &&
      (observation.layers.includes('L5_MODBUS') ||
        observation.layers.includes('L5_BACNET') ||
        observation.layers.includes('FIELD_CAN') ||
        observation.layers.includes('FIELD_PROFINET') ||
        observation.layers.includes('FIELD_ETHERNET_IP'))
    ) {
      findings.push(
        this.finding('OT_PLAINTEXT_PROTOCOL', 'MEDIUM', observation.key, observedAt, {
          layers: observation.layers,
          encrypted: observation.encrypted,
        }),
      );
    }
    return findings;
  }

  private detectTopologyBlockers(
    topology: NetworkTopologySnapshot,
    observedAt: string,
  ): NetworkFinding[] {
    const findings: NetworkFinding[] = [];
    const nowMs = Date.parse(observedAt);
    for (const node of topology.nodes) {
      if (node.kind === 'GATEWAY') {
        continue;
      }
      if (node.reachability === 'UNREACHABLE') {
        findings.push(
          this.finding('UNKNOWN_REACHABILITY', 'HIGH', `node:${node.id}`, observedAt, {
            nodeId: node.id,
            kind: node.kind,
          }),
        );
      }
      if (
        node.lastSeen !== undefined &&
        nowMs - Date.parse(node.lastSeen) > this.config.thresholds.staleNodeMs
      ) {
        findings.push(
          this.finding('UNKNOWN_REACHABILITY', 'MEDIUM', `node:${node.id}`, observedAt, {
            nodeId: node.id,
            lastSeen: node.lastSeen,
            staleMs: nowMs - Date.parse(node.lastSeen),
          }),
        );
      }
    }
    return findings;
  }

  private inspectSegments(
    envelope: UniversalIngressEnvelope,
    gatewayConfig: GatewayConfig,
    topology: NetworkTopologySnapshot,
    observedAt: string,
  ): readonly NetworkFinding[] {
    const segmentId = stringValue(envelope.metadata?.segmentId) || 'local';
    const segment = gatewayConfig.networkSegments.find((candidate) => candidate.id === segmentId);
    const findings: NetworkFinding[] = [];
    if (
      segment !== undefined &&
      segment.kind === 'DMZ' &&
      envelope.broadcast === true &&
      envelope.security.mode === 'OPEN_BROADCAST'
    ) {
      findings.push(
        this.finding('PLAINTEXT_OPEN_WIFI', 'HIGH', `segment:${segmentId}`, observedAt, {
          segmentId,
          transport: envelope.transport,
          mode: envelope.security.mode,
        }),
      );
    }
    if (segment !== undefined && !segment.allowPeerForwarding) {
      const peers = topology.links.filter((link) => link.from === segmentId);
      if (peers.length > 1 && envelope.broadcast === true) {
        findings.push(
          this.finding('VLAN_ISOLATION', 'LOW', `segment:${segmentId}`, observedAt, {
            segmentId,
            peers: peers.map((link) => link.to),
            reason: 'peer forwarding disabled for segment',
          }),
        );
      }
    }
    return findings;
  }

  private inspectAggregator(
    envelope: UniversalIngressEnvelope,
    observedAt: string,
  ): readonly NetworkFinding[] {
    const metadata = envelope.metadata ?? {};
    const aggregatorId = stringValue(metadata.aggregatorId ?? metadata.gatewayDeviceId);
    const embedded = stringArray(metadata.embeddedDeviceIds ?? metadata.devices);
    if (aggregatorId === '' || embedded.length === 0) {
      return [];
    }
    const duplicate = embedded.includes(envelope.deviceId) || embedded.includes(aggregatorId);
    if (!duplicate) {
      return [];
    }
    return [
      this.finding('AGGREGATOR_ID_COLLISION', 'HIGH', `aggregator:${aggregatorId}`, observedAt, {
        aggregatorId,
        envelopeDeviceId: envelope.deviceId,
        embeddedDeviceIds: embedded,
      }),
    ];
  }

  private classifyProbeFailure(result: ProbeResult): readonly NetworkFinding[] {
    if (result.reachable) {
      return [];
    }
    const error = (result.error ?? '').toLowerCase();
    const observedAt = normalizeTime(result.observedAt);
    const key = `probe:${result.target.nodeId}:${result.target.protocol}`;
    if (error.includes('timeout') || error.includes('timed out')) {
      return [
        this.finding('FIREWALL_DROP', 'HIGH', key, observedAt, {
          target: result.target,
          error: result.error,
        }),
      ];
    }
    if (error.includes('refused')) {
      return [
        this.finding('PORT_FORWARD_MISSING', 'MEDIUM', key, observedAt, {
          target: result.target,
          error: result.error,
        }),
      ];
    }
    return [
      this.finding('UNKNOWN_REACHABILITY', 'HIGH', key, observedAt, {
        target: result.target,
        error: result.error,
      }),
    ];
  }

  private planActions(
    findings: readonly NetworkFinding[],
    key: string,
    topology: NetworkTopologySnapshot | undefined,
    observedAt: string,
  ): readonly NetworkActionPlan[] {
    const plans: NetworkActionPlan[] = [];
    for (const finding of findings) {
      const type = actionForFinding(finding.type);
      const status =
        this.config.mode === 'AUTO_SAFE' && autoSafe(type) ? 'EXECUTED' : 'RECOMMENDED';
      plans.push({
        id: this.nextId('network-action'),
        type,
        severity: finding.severity,
        target: actionTarget(finding, key),
        reason: finding.message,
        createdAt: observedAt,
        status: this.config.mode === 'OBSERVE_ONLY' ? 'SUPPRESSED' : status,
        evidence: finding.evidence,
      });
      const companion = companionAction(finding.type);
      if (companion !== undefined) {
        plans.push({
          id: this.nextId('network-action'),
          type: companion,
          severity: finding.severity,
          target: actionTarget(finding, key),
          reason: `follow-up for ${finding.type}`,
          createdAt: observedAt,
          status:
            this.config.mode === 'AUTO_SAFE' && autoSafe(companion) ? 'EXECUTED' : 'RECOMMENDED',
          evidence: finding.evidence,
        });
      }
    }
    if (findings.length === 0 && topology !== undefined) {
      const staleProbeTargets = topology.nodes
        .filter((node) => node.kind !== 'GATEWAY' && node.reachability === 'UNKNOWN')
        .slice(0, 3);
      for (const node of staleProbeTargets) {
        plans.push({
          id: this.nextId('network-action'),
          type: 'PROBE_NEXT_HOP',
          severity: 'INFO',
          target: node.id,
          reason: 'node has unknown reachability',
          createdAt: observedAt,
          status: this.config.mode === 'OBSERVE_ONLY' ? 'SUPPRESSED' : 'RECOMMENDED',
          evidence: { nodeId: node.id, kind: node.kind },
        });
      }
    }
    this.rememberActions(plans);
    return plans;
  }

  private controlDecision(
    findings: readonly NetworkFinding[],
    actions: readonly NetworkActionPlan[],
    preferredRoute: RouteEntry | undefined,
  ): NetworkControlDecision {
    const executable = actions.filter((action) => action.status === 'EXECUTED');
    const holdRemoteFanout = executable.some((action) => action.type === 'HOLD_REMOTE_FANOUT');
    const throttleLowPriority = executable.some(
      (action) => action.type === 'THROTTLE_LOW_PRIORITY',
    );
    const requireEncryptedIngress = executable.some(
      (action) => action.type === 'REQUIRE_ENCRYPTED_INGRESS',
    );
    return {
      holdRemoteFanout,
      throttleLowPriority,
      requireEncryptedIngress,
      ...(preferredRoute === undefined ? {} : { preferredRoute }),
      findings,
      actions,
    };
  }

  private finding(
    type: NetworkBlockerType,
    severity: NetworkFindingSeverity,
    key: string,
    observedAt: string,
    evidence: Record<string, unknown>,
  ): NetworkFinding {
    return {
      id: this.nextId('network-finding'),
      type,
      severity,
      key,
      message: messageForFinding(type),
      observedAt,
      evidence,
    };
  }

  private rememberFindings(findings: readonly NetworkFinding[]): void {
    this.findings.push(...findings);
    if (this.findings.length > FINDING_RETENTION) {
      this.findings.splice(0, this.findings.length - FINDING_RETENTION);
    }
  }

  private rememberActions(actions: readonly NetworkActionPlan[]): void {
    this.actions.push(...actions);
    const max = Math.min(this.config.actionLimit, ACTION_RETENTION);
    if (this.actions.length > max) {
      this.actions.splice(0, this.actions.length - max);
    }
  }

  private nextId(prefix: string): string {
    return `${prefix}-${this.sequence++}`;
  }
}

function observationFromEnvelope(
  envelope: UniversalIngressEnvelope,
): NetworkIntelligenceObservation {
  const metadata = envelope.metadata ?? {};
  const segmentId = stringValue(metadata.segmentId) || 'local';
  const routeKey = `${segmentId}:${envelope.deviceId}:${envelope.transport}`;
  const latencyMs = numberValue(metadata.latencyMs);
  const packetLossRatio = numberValue(metadata.packetLossRatio);
  const reconnects = numberValue(metadata.reconnects);
  const jitterMs = numberValue(metadata.jitterMs);
  const throughputBps = numberValue(metadata.throughputBps);
  const rssiDbm = numberValue(metadata.rssiDbm);
  const mtuBytes = numberValue(metadata.mtuBytes);
  const multicastPacketsPerSecond = numberValue(metadata.multicastPacketsPerSecond);
  const controlPlaneAnomalyScore = numberValue(metadata.controlPlaneAnomalyScore);
  const vlanId = numberValue(metadata.vlanId);
  const family = addressFamily(metadata.addressFamily);
  const dhcpLeaseSeconds = numberValue(metadata.dhcpLeaseSeconds);
  const routingProtocol = routingProtocolValue(metadata.routingProtocol);
  const aggregatorId = stringValue(metadata.aggregatorId ?? metadata.gatewayDeviceId);
  return {
    key: routeKey,
    deviceId: envelope.deviceId,
    segmentId,
    routeKey,
    layers: layersFromEnvelope(envelope),
    broadcast: envelope.broadcast ?? envelope.transport === 'broadcast_udp',
    encrypted: envelope.security.mode !== 'OPEN_BROADCAST',
    embeddedDeviceIds: stringArray(metadata.embeddedDeviceIds ?? metadata.devices),
    observedAt: envelope.timestamp,
    metadata,
    ...(latencyMs === undefined ? {} : { latencyMs }),
    ...(packetLossRatio === undefined ? {} : { packetLossRatio }),
    ...(reconnects === undefined ? {} : { reconnects }),
    ...(jitterMs === undefined ? {} : { jitterMs }),
    ...(throughputBps === undefined ? {} : { throughputBps }),
    ...(rssiDbm === undefined ? {} : { rssiDbm }),
    ...(mtuBytes === undefined ? {} : { mtuBytes }),
    ...(multicastPacketsPerSecond === undefined ? {} : { multicastPacketsPerSecond }),
    ...(controlPlaneAnomalyScore === undefined ? {} : { controlPlaneAnomalyScore }),
    ...(vlanId === undefined ? {} : { vlanId }),
    ...(family === undefined ? {} : { addressFamily: family }),
    ...(dhcpLeaseSeconds === undefined ? {} : { dhcpLeaseSeconds }),
    ...(routingProtocol === undefined ? {} : { routingProtocol }),
    ...(aggregatorId.length === 0 ? {} : { aggregatorId }),
  };
}

function layersFromEnvelope(envelope: UniversalIngressEnvelope): readonly NetworkStackLayer[] {
  const metadata = envelope.metadata ?? {};
  const layers = new Set<NetworkStackLayer>(['APPLICATION']);
  if (
    envelope.transport === 'wifi_http' ||
    envelope.transport === 'mqtt' ||
    envelope.transport === 'websocket'
  ) {
    layers.add('L2_WIFI');
  }
  if (envelope.transport === 'ble') {
    layers.add('L2_BLE');
  }
  if (envelope.transport === 'lora') {
    layers.add('L2_LORA');
  }
  if (envelope.transport === 'esp_now') {
    layers.add('L2_ESP_NOW');
  }
  if (envelope.transport === 'zigbee') {
    layers.add('L2_ZIGBEE');
  }
  if (envelope.transport === 'serial') {
    layers.add('L5_SERIAL');
  }
  if (envelope.transport === 'mqtt') {
    layers.add('L4_TCP');
    layers.add('L5_MQTT');
  }
  if (envelope.transport === 'wifi_http') {
    layers.add('L4_TCP');
    layers.add('L5_HTTP');
  }
  if (envelope.transport === 'websocket') {
    layers.add('L4_TCP');
    layers.add('L5_WEBSOCKET');
  }
  if (envelope.transport === 'broadcast_udp') {
    layers.add('L2_WIFI');
    layers.add('L4_UDP');
  }
  if (envelope.transport === 'coap') {
    layers.add('L4_UDP');
    layers.add('L5_COAP');
  }
  if (envelope.transport === 'modbus_tcp') {
    layers.add('L4_TCP');
    layers.add('L5_MODBUS');
  }
  if (envelope.transport === 'modbus_rtu') {
    layers.add('L5_SERIAL');
    layers.add('L5_MODBUS');
  }
  if (envelope.transport === 'opcua') {
    layers.add('L4_TCP');
    layers.add('L5_OPCUA');
  }
  if (envelope.transport === 'bacnet_ip') {
    layers.add('L4_UDP');
    layers.add('L5_BACNET');
  }
  if (envelope.transport === 'can_bus') {
    layers.add('FIELD_CAN');
  }
  if (envelope.transport === 'dnp3') {
    layers.add('L4_TCP');
    layers.add('L5_DNP3');
  }
  if (envelope.transport === 'profinet') {
    layers.add('FIELD_PROFINET');
  }
  if (envelope.transport === 'ethernet_ip') {
    layers.add('L4_TCP');
    layers.add('FIELD_ETHERNET_IP');
  }
  const family = addressFamily(metadata.addressFamily);
  if (family === 'IPv4' || family === 'DUAL_STACK') {
    layers.add('L3_IPV4');
  }
  if (family === 'IPv6' || family === 'DUAL_STACK') {
    layers.add('L3_IPV6');
  }
  if (truthy(metadata.arpObserved)) {
    layers.add('L3_ARP');
  }
  if (truthy(metadata.ndpObserved)) {
    layers.add('L3_NDP');
  }
  if (metadata.vlanId !== undefined || truthy(metadata.vlanMismatch)) {
    layers.add('L3_VLAN');
  }
  if (truthy(metadata.dhcpObserved)) {
    layers.add('CONTROL_DHCP');
  }
  if (truthy(metadata.dhcpv6Observed)) {
    layers.add('CONTROL_DHCPV6');
  }
  if (truthy(metadata.slaacObserved) || truthy(metadata.slaacPrefixChanged)) {
    layers.add('CONTROL_SLAAC');
  }
  if (metadata.routingProtocol !== undefined || truthy(metadata.routeAdvertised)) {
    layers.add('CONTROL_ROUTING');
  }
  return [...layers].sort();
}

function probeLayers(protocol: string): readonly NetworkStackLayer[] {
  if (protocol === 'HTTP') {
    return ['L3_IPV4', 'L4_TCP', 'L5_HTTP', 'APPLICATION'];
  }
  if (protocol === 'APP_HEARTBEAT') {
    return ['L3_IPV4', 'L4_TCP', 'APPLICATION'];
  }
  return ['L3_IPV4', 'L4_TCP'];
}

function publicBaseline(baseline: MutableBaseline): LearnedNetworkBaseline {
  return {
    key: baseline.key,
    samples: baseline.samples,
    firstSeen: baseline.firstSeen,
    lastSeen: baseline.lastSeen,
    layers: [...baseline.layers].sort(),
    ewmaLatencyMs: baseline.ewmaLatencyMs,
    meanLatencyMs: baseline.latency.mean,
    latencyStddevMs: stddev(baseline.latency),
    ewmaPacketLossRatio: baseline.ewmaPacketLossRatio,
    meanPacketLossRatio: baseline.packetLoss.mean,
    packetLossStddev: stddev(baseline.packetLoss),
    ewmaReconnects: baseline.ewmaReconnects,
    meanReconnects: baseline.reconnects.mean,
    reconnectStddev: stddev(baseline.reconnects),
    ewmaJitterMs: baseline.ewmaJitterMs,
    availabilityScore: baseline.availabilityScore,
    routeScore: baseline.routeScore,
    encryptedRatio: ratio(baseline.encryptedCount, baseline.samples),
    broadcastRatio: ratio(baseline.broadcastCount, baseline.samples),
    addressFamilies: [...baseline.addressFamilies].sort(),
    routingProtocols: [...baseline.routingProtocols].sort(),
    aggregators: [...baseline.aggregators].sort(),
  };
}

function computePathScore(baseline: MutableBaseline): number {
  const latencyPenalty = clamp(baseline.ewmaLatencyMs / SCORE_MAX_LATENCY_MS, SCORE_MIN, SCORE_MAX);
  const reconnectPenalty = clamp(
    baseline.ewmaReconnects / SCORE_MAX_RECONNECTS,
    SCORE_MIN,
    SCORE_MAX,
  );
  const packetLossPenalty = clamp(baseline.ewmaPacketLossRatio, SCORE_MIN, SCORE_MAX);
  const encryptionBonus = ratio(baseline.encryptedCount, baseline.samples) * 0.08;
  const broadcastPenalty = ratio(baseline.broadcastCount, baseline.samples) * 0.08;
  return clamp(
    1 -
      latencyPenalty * 0.35 -
      packetLossPenalty * 0.35 -
      reconnectPenalty * 0.22 +
      encryptionBonus -
      broadcastPenalty,
    SCORE_MIN,
    SCORE_MAX,
  );
}

function topologyDigest(topology: NetworkTopologySnapshot | undefined): NetworkTopologyDigest {
  if (topology === undefined) {
    return {
      nodes: 0,
      links: 0,
      routes: 0,
      reachable: 0,
      degraded: 0,
      unreachable: 0,
      unknown: 0,
      protocols: {},
      segments: {},
    };
  }
  return {
    nodes: topology.nodes.length,
    links: topology.links.length,
    routes: topology.routes.length,
    reachable: countNodes(topology.nodes, 'REACHABLE'),
    degraded: countNodes(topology.nodes, 'DEGRADED'),
    unreachable: countNodes(topology.nodes, 'UNREACHABLE'),
    unknown: countNodes(topology.nodes, 'UNKNOWN'),
    protocols: countBy(topology.links, (link) => link.routingProtocol),
    segments: countBy(topology.nodes, (node) => node.kind),
  };
}

function countNodes(nodes: readonly NetworkNode[], state: ReachabilityState): number {
  return nodes.filter((node) => node.reachability === state).length;
}

function countBy<T>(items: readonly T[], key: (item: T) => string): Record<string, number> {
  const counts = new Map<string, number>();
  for (const item of items) {
    const value = key(item);
    counts.set(value, (counts.get(value) ?? 0) + 1);
  }
  return Object.fromEntries(
    [...counts.entries()].sort(([left], [right]) => left.localeCompare(right)),
  );
}

function groupBy<T>(items: readonly T[], key: (item: T) => string): Map<string, T[]> {
  const map = new Map<string, T[]>();
  for (const item of items) {
    const group = key(item);
    map.set(group, [...(map.get(group) ?? []), item]);
  }
  return map;
}

function emptyDecision(): NetworkControlDecision {
  return {
    holdRemoteFanout: false,
    throttleLowPriority: false,
    requireEncryptedIngress: false,
    findings: [],
    actions: [],
  };
}

function emptyStats(): RunningNumberStats {
  return { count: 0, mean: 0, m2: 0 };
}

function updateStats(stats: RunningNumberStats, value: number): RunningNumberStats {
  const count = stats.count + 1;
  const delta = value - stats.mean;
  const mean = stats.mean + delta / count;
  const delta2 = value - mean;
  return { count, mean, m2: stats.m2 + delta * delta2 };
}

function stddev(stats: RunningNumberStats): number {
  return Math.sqrt(stats.m2 / Math.max(1, stats.count - 1));
}

function zScore(value: number, stats: RunningNumberStats): number {
  if (stats.count < 2) {
    return 0;
  }
  const deviation = stddev(stats);
  if (deviation === 0) {
    return value === stats.mean ? 0 : Number.POSITIVE_INFINITY;
  }
  return Math.abs(value - stats.mean) / deviation;
}

function ewma(previous: number, value: number, alpha: number): number {
  return previous === 0 ? value : alpha * value + (1 - alpha) * previous;
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

function ratio(count: number, total: number): number {
  return total <= 0 ? 0 : count / total;
}

function normalizeTime(value: string | undefined): string {
  return value === undefined ? new Date().toISOString() : new Date(value).toISOString();
}

function routeBaselineKey(route: RouteEntry): string {
  return `${route.nextHop}:${route.destination}:${route.interfaceId ?? route.protocol}`;
}

function actionForFinding(type: NetworkBlockerType): NetworkActionType {
  const actions: Record<NetworkBlockerType, NetworkActionType> = {
    NAT_BOUNDARY: 'INSPECT_NAT_OR_PORT_FORWARD',
    FIREWALL_DROP: 'INSPECT_FIREWALL_RULE',
    PORT_FORWARD_MISSING: 'INSPECT_NAT_OR_PORT_FORWARD',
    DHCP_CHURN: 'PIN_DEVICE_TO_SEGMENT',
    SLAAC_PREFIX_CHANGE: 'PIN_DEVICE_TO_SEGMENT',
    VLAN_ISOLATION: 'PREFER_LOCAL_ROUTE',
    ROUTE_FLAP: 'PREFER_LOCAL_ROUTE',
    ASYMMETRIC_ROUTE: 'PROBE_NEXT_HOP',
    BROADCAST_NOISE: 'THROTTLE_LOW_PRIORITY',
    HIGH_LATENCY: 'THROTTLE_LOW_PRIORITY',
    HIGH_PACKET_LOSS: 'HOLD_REMOTE_FANOUT',
    HIGH_RECONNECT_RATE: 'PREFER_LOCAL_ROUTE',
    MTU_BLACKHOLE: 'THROTTLE_LOW_PRIORITY',
    AGGREGATOR_ID_COLLISION: 'SPLIT_AGGREGATOR_STREAM',
    PLAINTEXT_OPEN_WIFI: 'REQUIRE_ENCRYPTED_INGRESS',
    OT_PLAINTEXT_PROTOCOL: 'REQUIRE_ENCRYPTED_INGRESS',
    MULTICAST_STORM: 'THROTTLE_LOW_PRIORITY',
    ROGUE_DHCP: 'RAISE_OPERATOR_ALERT',
    ARP_SPOOFING: 'RAISE_OPERATOR_ALERT',
    CONTROL_PLANE_ANOMALY: 'RAISE_OPERATOR_ALERT',
    UNKNOWN_REACHABILITY: 'PROBE_NEXT_HOP',
  };
  return actions[type];
}

function companionAction(type: NetworkBlockerType): NetworkActionType | undefined {
  if (type === 'HIGH_PACKET_LOSS' || type === 'UNKNOWN_REACHABILITY') {
    return 'PROBE_NEXT_HOP';
  }
  if (
    type === 'PLAINTEXT_OPEN_WIFI' ||
    type === 'OT_PLAINTEXT_PROTOCOL' ||
    type === 'AGGREGATOR_ID_COLLISION' ||
    type === 'ROGUE_DHCP' ||
    type === 'ARP_SPOOFING' ||
    type === 'CONTROL_PLANE_ANOMALY'
  ) {
    return 'RAISE_OPERATOR_ALERT';
  }
  if (type === 'ROUTE_FLAP' || type === 'ASYMMETRIC_ROUTE') {
    return 'HOLD_REMOTE_FANOUT';
  }
  return undefined;
}

function autoSafe(type: NetworkActionType): boolean {
  return (
    type === 'HOLD_REMOTE_FANOUT' ||
    type === 'THROTTLE_LOW_PRIORITY' ||
    type === 'PREFER_LOCAL_ROUTE' ||
    type === 'UPDATE_BASELINE'
  );
}

function actionTarget(finding: NetworkFinding, fallback: string): string {
  const deviceId = stringValue(finding.evidence.deviceId);
  const destination = stringValue(finding.evidence.destination);
  const segmentId = stringValue(finding.evidence.segmentId);
  return deviceId || destination || segmentId || fallback;
}

function messageForFinding(type: NetworkBlockerType): string {
  const messages: Record<NetworkBlockerType, string> = {
    NAT_BOUNDARY:
      'NAT boundary detected; inbound reachability may require relay or port forwarding',
    FIREWALL_DROP: 'Probe or traffic pattern indicates firewall drop or silent filtering',
    PORT_FORWARD_MISSING:
      'Endpoint refused traffic; service binding or port forwarding may be missing',
    DHCP_CHURN: 'Address lease churn is changing device reachability',
    SLAAC_PREFIX_CHANGE: 'IPv6 SLAAC prefix or temporary address behavior changed',
    VLAN_ISOLATION: 'VLAN or segment policy is limiting peer reachability',
    ROUTE_FLAP: 'Route next-hop or metric is changing inside the flap window',
    ASYMMETRIC_ROUTE: 'Forward and return paths appear asymmetric',
    BROADCAST_NOISE: 'Broadcast traffic is dominating the learned path profile',
    HIGH_LATENCY: 'Latency exceeds learned or configured limits',
    HIGH_PACKET_LOSS: 'Packet loss exceeds learned or configured limits',
    HIGH_RECONNECT_RATE: 'Reconnect rate exceeds learned or configured limits',
    MTU_BLACKHOLE: 'MTU or fragmentation symptoms were observed',
    AGGREGATOR_ID_COLLISION: 'Aggregator identity collides with an embedded device identity',
    PLAINTEXT_OPEN_WIFI: 'Plaintext broadcast on WiFi creates a high-risk ingress path',
    OT_PLAINTEXT_PROTOCOL:
      'Legacy OT protocol observed without an authenticated or encrypted gateway boundary',
    MULTICAST_STORM: 'Multicast or listener traffic rate exceeds the learned safe profile',
    ROGUE_DHCP: 'DHCP authority changed or rogue DHCP symptoms were observed',
    ARP_SPOOFING: 'Address-to-MAC mapping conflict suggests spoofing or duplicate assignment',
    CONTROL_PLANE_ANOMALY: 'Control-plane behavior exceeded the configured anomaly score',
    UNKNOWN_REACHABILITY: 'Node reachability is unknown or failed',
  };
  return messages[type];
}

function scoreReachability(state: ReachabilityState): number {
  const scores: Record<ReachabilityState, number> = {
    REACHABLE: 1,
    DEGRADED: 0.55,
    UNKNOWN: 0.35,
    UNREACHABLE: 0,
  };
  return scores[state];
}

function protocolPreference(protocol: RoutingProtocol): number {
  const scores: Record<RoutingProtocol, number> = {
    STATIC: 0.85,
    BGP: 0.75,
    OSPF: 0.8,
    RIP: 0.45,
    MESH: 0.65,
    MQTT_BROKER: 0.8,
    LORA_GATEWAY: 0.55,
    ESP_NOW_PEER: 0.7,
    SERIAL_MULTIPLEX: 0.75,
    COAP_PROXY: 0.68,
    MODBUS_GATEWAY: 0.62,
    OPCUA_SERVER: 0.82,
    BACNET_ROUTER: 0.58,
    CAN_GATEWAY: 0.6,
    ZIGBEE_COORDINATOR: 0.63,
    DNP3_OUTSTATION: 0.7,
    PROFINET_IO: 0.78,
    ETHERNET_IP_CIP: 0.72,
    UNKNOWN: 0.4,
  };
  return scores[protocol];
}

function numberValue(value: unknown): number | undefined {
  return typeof value === 'number' && Number.isFinite(value) ? value : undefined;
}

function stringValue(value: unknown): string {
  return typeof value === 'string' ? value : '';
}

function truthy(value: unknown): boolean {
  return value === true || value === 'true' || value === 1;
}

function stringArray(value: unknown): readonly string[] {
  if (!Array.isArray(value)) {
    return [];
  }
  return value.filter((item): item is string => typeof item === 'string' && item.length > 0);
}

function routingProtocolValue(value: unknown): RoutingProtocol | undefined {
  if (typeof value !== 'string') {
    return undefined;
  }
  const upper = value.toUpperCase();
  if (
    upper === 'STATIC' ||
    upper === 'BGP' ||
    upper === 'OSPF' ||
    upper === 'RIP' ||
    upper === 'MESH' ||
    upper === 'MQTT_BROKER' ||
    upper === 'LORA_GATEWAY' ||
    upper === 'ESP_NOW_PEER' ||
    upper === 'SERIAL_MULTIPLEX' ||
    upper === 'COAP_PROXY' ||
    upper === 'MODBUS_GATEWAY' ||
    upper === 'OPCUA_SERVER' ||
    upper === 'BACNET_ROUTER' ||
    upper === 'CAN_GATEWAY' ||
    upper === 'ZIGBEE_COORDINATOR' ||
    upper === 'DNP3_OUTSTATION' ||
    upper === 'PROFINET_IO' ||
    upper === 'ETHERNET_IP_CIP' ||
    upper === 'UNKNOWN'
  ) {
    return upper;
  }
  return undefined;
}

function addressFamily(value: unknown): NetworkIntelligenceObservation['addressFamily'] {
  if (value === 'IPv4' || value === 'IPv6' || value === 'DUAL_STACK' || value === 'UNKNOWN') {
    return value;
  }
  return undefined;
}
